cc_library(
  name = "lib",
  srcs = ["callback_scheduler.cpp", "simple_thread_executor.cpp"],
  hdrs = ["callback_scheduler.h", "callback_executor.h", "simple_thread_executor.h"],
  visibility = ["//visibility:public"]
)
